### ISSUE TITLE
[BUG] preprocessing crashes with TST_Srinivasan_2021-10_QS

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

running preprocessing (aka dataset checker) crashes when run with TST_Srinivasan_2021-10_QS dataset.

output gives: 
```
[...]
Traceback (most recent call last):
  File "/home/sbancal/IT4R/CCFatiguePlatform/backend/preprocessing/tst_preprocessing.py", line 87, in <module>
    experiment = Experiment(experiment_raw_fp_folder, logger)
  File "/home/sbancal/IT4R/CCFatiguePlatform/backend/preprocessing/tst_data_lib.py", line 116, in __init__
    self._validate_measures()
  File "/home/sbancal/IT4R/CCFatiguePlatform/backend/preprocessing/tst_data_lib.py", line 1261, in _validate_measures
    fracture = Experiment.__get_val_at(self.experiment, "general>fracture")
  File "/home/sbancal/IT4R/CCFatiguePlatform/backend/preprocessing/tst_data_lib.py", line 1357, in __get_val_at
    obj = obj[key]
KeyError: 'fracture'
```

### Expected Behavior

preprocessing must work, even if the dataset contains errors.

### Steps To Reproduce

```bash
cd backend
poetry run python3 preprocessing/tst_preprocessing.py tmp/TST_Srinivasan_2021-10_QS
```

or upload TST_Srinivasan_2021-10_QS.zip on https://ccfatigue-test.epfl.ch/fatigue_database/data_upload

### Environment

```markdown
any
```

**Comment by sbancal** [comment]
`TST_2021-10_QS_metadata.xlsx` doesn't follow https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/Data/TST_Data_Template.xls .
Line 3 named _Definition_ must be deleted in order to be processed.

**Comment by vsdharun** [comment]
@sbancal Hi, Thanks for the advice..
Now, I am able to upload the data set, it passed :)
